In [24]:
import numpy as np
import pandas as pd

# for model evaluation 
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, r2_score

# for model
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestRegressor


# for cross validation
from sklearn.model_selection import KFold

# for MSE
from sklearn.metrics import mean_squared_error

# log loss
from numpy.linalg import inv


In [25]:
url = "https://raw.githubusercontent.com/AliceLiu17/KPMG-Sustainable-Future/main/Data/df_FINAL_CLEANED.csv"
df = pd.read_csv(url)
df.head()

zip_code  population  house_value  household_income  \
0     75201       18460       630100             94872   
1     75202        2931       269200             92500   
2     75203       18211       108600             37418   
3     75204       45140       378600             81914   
4     75205       26531      1212700            159076   

   residential_business_ratio  ev_registration_count  evcs_count  \
0                           5                    536           4   
1                           3                     83           1   
2                          11                     35           1   
3                          20                    517           0   
4                          13                    540           1   

   Hispanic Population  Black Population  Asian Population  \
0                 1043              1627               445   
1                  255               278                64   
2                 9359              5586                76   
3                 7292              3775              1745   
4                 1385               384               937   

   American Indian Population  Hawaiian Population  Other Population  \
0                         110                   16               328   
1                          31                    4                55   
2                         236                   40              5344   
3                         323                   44              3358   
4                         163                   14               444   

   Female Population  Number of Businesses  shops  parking lots  Gas Stations  
0               4339                  2455    0.0         252.0             1  
1                739                   585    0.0          91.0             1  
2               7535                   245    0.0          17.0             4  
3              12623                  1383    7.0         220.0             7  
4              12080                  1101    0.0         136.0             2

In [20]:
#### FOR LOOKING AT BEST MODEL, could possibly use the entire dataset rather than the train/test split
# created training and testing data sets
y = df["ev_registration_count"]
X = df.drop(columns = ["ev_registration_count", "evcs_count"], axis = 1)

# split data into training and testing data 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.15, random_state = 1234)

print(X_train.shape)
print(X_test.shape)

# create model to train your data in....
model = RandomForestRegressor(n_estimators = 10, random_state = 0)

# train and evaulate the model's performance 
# KFold approach:
num_folds = 5 # 5 FOLDS
folds = KFold(n_splits = num_folds, random_state = None)
cv_acc_scores = []
cv_r2_scores = []

for train_row_index, test_row_index in folds.split(X_train):
    # our new partition of X_train and X_val
    X_train_new  = X_train.iloc[train_row_index] 
    X_val = X_train.iloc[test_row_index]
    
    # our new partition of y_train and y_val
    y_train_new = y_train.iloc[train_row_index]
    y_val = y_train.iloc[test_row_index]

    model.fit(X_train_new, y_train_new)
    predictions = model.predict(X_val)
    print(predictions)

    #iteration_accuracy = accuracy_score(predictions , y_val)
    iteration_r2 = r2_score(predictions, y_val)
    #cv_acc_scores.append(iteration_accuracy)
     
        
#for i in range(len(cv_acc_scores)):
    #print('Accuracy score for iteration {0}: {1}'.format(i+1, cv_acc_scores[i]))

for i in range(len(cv_r2_scores)):
    print('r2 score for iteration {0}: {1}'.format(i+1, cv_r2_scores[i]))

#avg_scores = sum(cv_acc_scores)/num_folds
#print('\nAverage accuracy score: {}'.format(avg_scores))
######

(40, 16)
(8, 16)
[ 31.6 161.5  30.4 118.  351.6 160.  389.8  68.1]
[ 85.3 238.2  51.6  94.3 279.7 245.9 237.3  41. ]
[320.9  84.2 179.4 374.5 244.  247.2  57.2 207.1]
[292.4  45.2 218.4 314.   35.5 103.1 106.4 288. ]
[274.5 143.7 132.2 212.9 241.2 147.6  63.4 241.5]


In [23]:
##########

# created training and testing data sets
y = df["ev_registration_count"]
X = df.drop(columns = ["ev_registration_count", "evcs_count"], axis = 1)

# split data into training and testing data 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 50)

# create the model
model = RandomForestRegressor(n_estimators = 10, random_state = 0)

# fit the model to the training data
model.fit(X_train, y_train)

# make prediction on the test data
y_pred = model.predict(X_test)

# call the mean_squared_error() with y_test and prediction
model_mse = mean_squared_error(y_test, y_pred)

# accuracy score:
# mse_acc_score = accuracy_score(y_test, y_pred)
# r2 score:
mse_r2 = r2_score(y_test, y_pred)

print("MSE: {0}".format(model_mse))
#print("Accuracy Score: {0}".format(mse_acc_score))
print("R2 Score: {0}".format(mse_r2))

MSE: 5223.493
R2 Score: 0.5181652897745932


In [26]:
# created training and testing data sets
y = df["ev_registration_count"]
X = df.drop(columns = ["ev_registration_count", "evcs_count"], axis = 1)

# split data into training and testing data 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 50)

# create the model
model = RandomForestRegressor(n_estimators = 31, max_features = 'sqrt', max_depth = 4, min_samples_split = 2, min_samples_leaf = 2, bootstrap = True, random_state = 48)

# fit the model to the training data
model.fit(X_train, y_train)

# make prediction on the test data
y_pred = model.predict(X_test)

# call the mean_squared_error() with y_test and prediction
model_rmse = mean_squared_error(y_test, y_pred, squared = False)

# r2 score:
rmse_r2 = r2_score(y_test, y_pred)

print("RMSE: {0}".format(model_rmse))
print("R2 Score: {0}".format(rmse_r2))

RMSE: 68.400502006751
R2 Score: 0.5684256317060721


In [10]:
parameters = {
    'n_estimators': [25, 50, 100, 150, 200, 250],
    'max_depth': [1,2,3,4],
}
regr = RandomForestRegressor(random_state=0)

clf = GridSearchCV(regr, parameters)
clf.fit(X_train, y_train)
y_pred_train = clf.predict(X_train)
mean_squared_error(y_train, y_pred_train)
print(clf.best_score_)
print(clf.best_params_)

0.6345032755079464
{'max_depth': 4, 'n_estimators': 25}


In [11]:
# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 5, stop = 50, num = 40)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(2, 10, num = 8)]
max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4]
# Method of selecting samples for training each tree
bootstrap = [True, False]
# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}

rf = RandomForestRegressor()
# Random search of parameters, using 3 fold cross validation, 
# search across 100 different combinations, and use all available cores
rf_random = RandomizedSearchCV(estimator = rf, param_distributions = random_grid, n_iter = 100, cv = 5, verbose=2, random_state=42, n_jobs = -1)
# Fit the random search model
rf_random.fit(X_train, y_train)
rf_random.best_params_

Fitting 5 folds for each of 100 candidates, totalling 500 fits


{'n_estimators': 31,
 'min_samples_split': 2,
 'min_samples_leaf': 2,
 'max_features': 'sqrt',
 'max_depth': None,
 'bootstrap': False}

In [13]:
def evaluate(model, test_features, test_labels):
    predictions = model.predict(test_features)
    errors = abs(predictions - test_labels)
    mape = 100 * np.mean(errors / test_labels)
    accuracy = 100 - mape
    print('Model Performance')
    print('Average Error: {:0.4f} degrees.'.format(np.mean(errors)))
    print('Accuracy = {:0.2f}%.'.format(accuracy))
    
    return accuracy

base_model = RandomForestRegressor(n_estimators = 10, random_state = 42)
base_model.fit(X_train, y_train)
base_accuracy = evaluate(base_model, X_test, y_test)

best_random = rf_random.best_estimator_
random_accuracy = evaluate(best_random, X_test, y_test)

print('Improvement of {:0.2f}%.'.format( 100 * (random_accuracy - base_accuracy) / base_accuracy))

Model Performance
Average Error: 69.0700 degrees.
Accuracy = -7.30%.
Model Performance
Average Error: 11.0425 degrees.
Accuracy = 83.93%.
Improvement of -1250.47%.


In [14]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [28]:
url = "/content/drive/MyDrive/BTT AI: KPMG /Colab/2030 Edition[Unverified].csv"
df_future = pd.read_csv(url)
df_future.head()

Unnamed: 0  zip_code  population  house_value  household_income  \
0           0     75201       18460       630100             94872   
1           1     75202        2931       269200             92500   
2           2     75203       18211       108600             37418   
3           3     75204       45140       378600             81914   
4           4     75205       26531      1212700            159076   

   residential_business_ratio  ev_registration_count  evcs_count  \
0                           5                    536           4   
1                           3                     83           1   
2                          11                     35           1   
3                          20                    517           0   
4                          13                    540           1   

   Hispanic Population  Black Population  ...  2030 Female Population  \
0                 1043              1627  ...                 4859.68   
1                  255               278  ...                  827.68   
2                 9359              5586  ...                 8439.20   
3                 7292              3775  ...                14137.76   
4                 1385               384  ...                13529.60   

   2030 house_value  2030 household_income  2030 residential_business_ratio  \
0       309113.1978           46542.116016                         2.452890   
1       132063.5976           45378.465000                         1.471734   
2        53276.7708           18356.447604                         5.396358   
3       185732.8308           40185.206292                         9.811560   
4       594923.9406           78039.185928                         6.377514   

   2030 ev_registration_count  2030 evcs_count   2030 Number of Businesses  \
0                  262.949808         1.962312                 1204.368990   
1                   40.717974         0.490578                  286.988130   
2                   17.170230         0.490578                  120.191610   
3                  253.628826         0.000000                  678.469374   
4                  264.912120         0.490578                  540.126378   

   2030 shops  2030 parking lots  2030 Gas Stations  
0    0.000000         123.625656           0.490578  
1    0.000000          44.642598           0.490578  
2    0.000000           8.339826           1.962312  
3    3.434046         107.927160           3.434046  
4    0.000000          66.718608           0.981156  

[5 rows x 36 columns]

In [29]:
X_new = df_future.drop(columns = ["ev_registration_count", "evcs_count", "Unnamed: 0"], axis = 1)
y_future_pred = model.predict(X_new)

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
-  2030 Number of Businesses
- 2030 American Indian Population
- 2030 Asian Population
- 2030 Black Population
- 2030 Female Population
- ...
Feature names must be in the same order as they were in fit.

  warnings.warn(message, FutureWarning)


ValueError: ignored